name: I18n Merge

on:
  push:
    branches:
      - main

jobs:
  merge_i18n:
    name: Merge i18n translation files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Merge Locale Files
        uses: larrrssss/i18n-merge@v1.1.2
        id: merge
        with:
          workspace: ${{ github.workspace }}
          root: '/'
          output_file_path: 'output.json'
          locales_file_path: 'locales.json'
          base_file_name: 'base.json'

      # Push the output file to the master branch. You can update this step to handle the output file with your own custom logic.
      - name: Push Output File
        if: ${{ steps.merge.outputs.changes_detected == '1' }}
        env:
          CI_COMMIT_MESSAGE: I18n Translation Merge
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push